-- MySQL Script generated by MySQL Workbench
-- Tue May 28 12:34:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classolympians
-- -----------------------------------------------------

-- Create the schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS `classolympians` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `classolympians` ;

-- -----------------------------------------------------
-- Drop tables if they exist in the correct order
-- -----------------------------------------------------

-- Drop child tables first
DROP TABLE IF EXISTS `classolympians`.`Athlète_has_DisciplineSportive`;
DROP TABLE IF EXISTS `classolympians`.`Résultats`;
DROP TABLE IF EXISTS `classolympians`.`EvenementSportif`;

-- Drop parent tables next
DROP TABLE IF EXISTS `classolympians`.`Athlète`;
DROP TABLE IF EXISTS `classolympians`.`DisciplineSportive`;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Create tables
-- -----------------------------------------------------

-- Table `classolympians`.`Athlète`
CREATE TABLE IF NOT EXISTS `classolympians`.`Athlète` (
  `idAthlète` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Pays` VARCHAR(45) NULL,
  `Âge` INT NULL,
  `Sexe` CHAR(1) NULL,
  PRIMARY KEY (`idAthlète`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- Table `classolympians`.`DisciplineSportive`
CREATE TABLE IF NOT EXISTS `classolympians`.`DisciplineSportive` (
  `idDisciplineSportive` INT NOT NULL AUTO_INCREMENT,
  `Nom_Discipline` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplineSportive`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- Table `classolympians`.`EvenementSportif`
CREATE TABLE IF NOT EXISTS `classolympians`.`EvenementSportif` (
  `idEvenementSportif` INT NOT NULL AUTO_INCREMENT,
  `Nom_Evenement` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Heure` TIME NULL,
  `Lieu` VARCHAR(45) NULL,
  `DisciplineSportive_idDisciplineSportive` INT NOT NULL,
  PRIMARY KEY (`idEvenementSportif`),
  INDEX `fk_EvenementSportif_DisciplineSportive1_idx` (`DisciplineSportive_idDisciplineSportive`)
) ENGINE=InnoDB;

ALTER TABLE `classolympians`.`EvenementSportif`
  ADD CONSTRAINT `fk_EvenementSportif_DisciplineSportive1`
  FOREIGN KEY (`DisciplineSportive_idDisciplineSportive`)
  REFERENCES `classolympians`.`DisciplineSportive` (`idDisciplineSportive`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

SHOW WARNINGS;

-- Table `classolympians`.`Résultats`
CREATE TABLE IF NOT EXISTS `classolympians`.`Résultats` (
  `idRésultats` INT NOT NULL AUTO_INCREMENT,
  `EvenementSportif_idEvenementSportif` INT NOT NULL,
  `Athlète_idAthlète` INT NOT NULL,
  `Temps` DATE NULL,
  `Score` INT NULL,
  `Médaille` VARCHAR(45) NULL,
  PRIMARY KEY (`idRésultats`),
  INDEX `fk_Résultats_EvenementSportif1_idx` (`EvenementSportif_idEvenementSportif`),
  INDEX `fk_Résultats_Athlète1_idx` (`Athlète_idAthlète`),
  CONSTRAINT `fk_Résultats_EvenementSportif1`
    FOREIGN KEY (`EvenementSportif_idEvenementSportif`)
    REFERENCES `classolympians`.`EvenementSportif` (`idEvenementSportif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Résultats_Athlète1`
    FOREIGN KEY (`Athlète_idAthlète`)
    REFERENCES `classolympians`.`Athlète` (`idAthlète`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- Table `classolympians`.`Athlète_has_DisciplineSportive`
CREATE TABLE IF NOT EXISTS `classolympians`.`Athlète_has_DisciplineSportive` (
  `Athlète_idAthlète` INT NOT NULL,
  `DisciplineSportive_idDisciplineSportive` INT NOT NULL,
  PRIMARY KEY (`Athlète_idAthlète`, `DisciplineSportive_idDisciplineSportive`),
  INDEX `fk_Athlète_has_DisciplineSportive_DisciplineSportive1_idx` (`DisciplineSportive_idDisciplineSportive`),
  INDEX `fk_Athlète_has_DisciplineSportive_Athlète1_idx` (`Athlète_idAthlète`),
  CONSTRAINT `fk_Athlète_has_DisciplineSportive_Athlète1`
    FOREIGN KEY (`Athlète_idAthlète`)
    REFERENCES `classolympians`.`Athlète` (`idAthlète`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Athlète_has_DisciplineSportive_DisciplineSportive1`
    FOREIGN KEY (`DisciplineSportive_idDisciplineSportive`)
    REFERENCES `classolympians`.`DisciplineSportive` (`idDisciplineSportive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- Exemple :
INSERT INTO athlète (Nom, Prénom, Pays, Âge, Sexe)
VALUES ('RINER', 'Teddy', 'France', 35, 'M');
