-- MySQL Script generated by MySQL Workbench
-- Tue May 28 12:34:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Athlète`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Athlète` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Athlète` (
  `idAthlète` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Pays` VARCHAR(45) NULL,
  `Âge` INT NULL,
  `Sexe` VARCHAR(45) NULL,
  PRIMARY KEY (`idAthlète`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DisciplineSportive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DisciplineSportive` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`DisciplineSportive` (
  `idDisciplineSportive` INT NOT NULL,
  `Nom_Discipline` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplineSportive`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ÉvénementSportif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ÉvénementSportif` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ÉvénementSportif` (
  `idÉvénementSportif` INT NOT NULL,
  `Nom_Evènement` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Heure` DATE NULL,
  `Lieu` VARCHAR(45) NULL,
  `DisciplineSportive_idDisciplineSportive` INT NOT NULL,
  PRIMARY KEY (`idÉvénementSportif`),
  INDEX `fk_ÉvénementSportif_DisciplineSportive1_idx` (`DisciplineSportive_idDisciplineSportive` ASC) VISIBLE,
  CONSTRAINT `fk_ÉvénementSportif_DisciplineSportive1`
    FOREIGN KEY (`DisciplineSportive_idDisciplineSportive`)
    REFERENCES `mydb`.`DisciplineSportive` (`idDisciplineSportive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Résultats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Résultats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Résultats` (
  `idRésultats` INT NOT NULL,
  `ÉvénementSportif_idÉvénementSportif` INT NOT NULL,
  `Athlète_idAthlète` INT NOT NULL,
  `Temps` DATE NULL,
  `Score` INT NULL,
  `Médaille` VARCHAR(45) NULL,
  PRIMARY KEY (`idRésultats`),
  INDEX `fk_Résultats_ÉvénementSportif1_idx` (`ÉvénementSportif_idÉvénementSportif` ASC) VISIBLE,
  INDEX `fk_Résultats_Athlète1_idx` (`Athlète_idAthlète` ASC) VISIBLE,
  CONSTRAINT `fk_Résultats_ÉvénementSportif1`
    FOREIGN KEY (`ÉvénementSportif_idÉvénementSportif`)
    REFERENCES `mydb`.`ÉvénementSportif` (`idÉvénementSportif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Résultats_Athlète1`
    FOREIGN KEY (`Athlète_idAthlète`)
    REFERENCES `mydb`.`Athlète` (`idAthlète`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Athlète_has_DisciplineSportive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Athlète_has_DisciplineSportive` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Athlète_has_DisciplineSportive` (
  `Athlète_idAthlète` INT NOT NULL,
  `DisciplineSportive_idDisciplineSportive` INT NOT NULL,
  PRIMARY KEY (`Athlète_idAthlète`, `DisciplineSportive_idDisciplineSportive`),
  INDEX `fk_Athlète_has_DisciplineSportive_DisciplineSportive1_idx` (`DisciplineSportive_idDisciplineSportive` ASC) VISIBLE,
  INDEX `fk_Athlète_has_DisciplineSportive_Athlète1_idx` (`Athlète_idAthlète` ASC) VISIBLE,
  CONSTRAINT `fk_Athlète_has_DisciplineSportive_Athlète1`
    FOREIGN KEY (`Athlète_idAthlète`)
    REFERENCES `mydb`.`Athlète` (`idAthlète`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Athlète_has_DisciplineSportive_DisciplineSportive1`
    FOREIGN KEY (`DisciplineSportive_idDisciplineSportive`)
    REFERENCES `mydb`.`DisciplineSportive` (`idDisciplineSportive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
